export const properties = [
  {
    id: 1,
    title: "Modern Apartment",
    location: "New York",
    bedrooms: "1 bed",
    price: 120,
    myImage: "/assets/images/modern-apartment.jpg",
  },
  {
    id: 2,
    title: "Beach House",
    location: "Thailand",
    bedrooms: "2 bed",
    price: 200,
    myImage: "/assets/images/near-beach.jpg",
  },
  {
    id: 3,
    title: "Near the City",
    location: "Goa",
    bedrooms: "3 bed",
    price: 250,
    myImage: "/assets/images/near-city.jpg",
  },
  {
    id: 4,
    title: "On the Hills",
    bedrooms: "4 bed",
    location: "Mumbai",
    price: 350,
    myImage: "/assets/images/on-hills.jpg",
  },
  {
    id: 5,
    title: "Modern Apartment",
    location: "Dubai",
    bedrooms: "1 bed",
    price: 400,
    myImage: "/assets/images/modern-apartment.jpg",
  },
  {
    id: 6,
    title: "Beach House",
    location: "Paris",
    bedrooms: "2 bed",
    price: 500,
    myImage: "/assets/images/near-beach.jpg",
  },
  {
    id: 7,
    title: "Near the City",
    location: "Delhi",
    bedrooms: "3 bed",
    price: 250,
    myImage: "/assets/images/near-city.jpg",
  },
  {
    id: 8,
    title: "On the Hills",
    bedrooms: "4 bed",
    location: "Mumbai",
    price: 350,
    myImage: "/assets/images/on-hills.jpg",
  },
];
